### ISSUE TITLE
How to configure linthub to use local checkstyle

### ISSUE THREAD

**Issue by tallnato** [linthubot/linthub-demo#23]
Hi,
I'm trying to use the linthub.yml file with a local checkstyle but it seams that it is not working.
The file is as follows:
```yml
java:
  lint: true
  config: checkstyle.xml
```

You can see the PR here: https://github.com/tallnato/hello-linthub/pull/2

But nothing is verified.

Also, isn't supposed to the @linthubot to comment on the pull requests?
Thanks 🙂
